global:
  enabled: true
  synopsisJSON: <<PWD>>/config/__generated/<<OS>>/git.json
  flagBlacklist:
    - --help
operations:
  clone:
    enabled: true 
    synopsisJSON: <<PWD>>/config/__generated/<<OS>>/git-clone.json
    execution:
      prompt: true
      shouldAppendRepositoryArg: true
      targetCommand: <<PWD>>/example/git-clone-hello
  init:
    enabled: true 
    synopsisJSON: <<PWD>>/config/__generated/<<OS>>/git-init.json
    globalFlagBlacklist:
      - --bare
    flagBlacklist:
      - --bare
    execution:
      prompt: true
      shouldAppendRepositoryArg: true
      targetCommand: <<PWD>>/example/git-init-hello

